// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace swipefilm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718222818_AddServerItemIdAndMachineIdentifier")]
    partial class AddServerItemIdAndMachineIdentifier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoRequestOnSwipe")
                        .HasColumnType("boolean");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordId")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("JellyfinUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MovieQuotaDays")
                        .HasColumnType("integer");

                    b.Property<int?>("MovieQuotaLimit")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<long>("Permissions")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PlexUserId")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TelegramChatId")
                        .HasColumnType("text");

                    b.Property<int?>("TvQuotaDays")
                        .HasColumnType("integer");

                    b.Property<int?>("TvQuotaLimit")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("swipefilm.Models.AppSettings", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Key = "IsSetupComplete",
                            Value = "false"
                        });
                });

            modelBuilder.Entity("swipefilm.Models.DiscoveryCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Availability")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<int>>("TmdbIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SectionId")
                        .IsUnique()
                        .HasDatabaseName("idx_discoverycache_user_section");

                    b.ToTable("DiscoveryCaches");
                });

            modelBuilder.Entity("swipefilm.Models.MediaRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProcessedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("QualityProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RootFolderPath")
                        .HasColumnType("text");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedByUserId");

                    b.HasIndex("MovieId", "Status")
                        .HasDatabaseName("idx_requests_movieid_status");

                    b.HasIndex("SeriesId", "Status")
                        .HasDatabaseName("idx_requests_seriesid_status");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_requests_userid_status");

                    b.ToTable("MediaRequests", t =>
                        {
                            t.HasCheckConstraint("ck_mediarequests_movie_xor_series", "(\"MovieId\" IS NOT NULL) <> (\"SeriesId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("swipefilm.Models.MediaRequestSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaRequestId", "SeasonNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_mediarequestseasons_requestid_seasonnumber");

                    b.ToTable("MediaRequestSeasons");
                });

            modelBuilder.Entity("swipefilm.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("CastTop5")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Directors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("text");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer");

                    b.Property<float>("TmdbPopularity")
                        .HasColumnType("real");

                    b.Property<float>("TmdbRating")
                        .HasColumnType("real");

                    b.Property<int>("TmdbVoteCount")
                        .HasColumnType("integer");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CachedAt")
                        .HasDatabaseName("idx_movies_cachedat");

                    b.HasIndex("ContentType")
                        .HasDatabaseName("idx_movies_contenttype");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasDatabaseName("idx_movies_tmdbid");

                    b.HasIndex("TmdbRating", "TmdbPopularity")
                        .HasDatabaseName("idx_movies_rating_popularity");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("swipefilm.Models.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("CastTop5")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateOnly?>("FirstAirDate")
                        .HasColumnType("date");

                    b.Property<string[]>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("NumberOfEpisodes")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfSeasons")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("text");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer");

                    b.Property<float>("TmdbPopularity")
                        .HasColumnType("real");

                    b.Property<float>("TmdbRating")
                        .HasColumnType("real");

                    b.Property<int>("TmdbVoteCount")
                        .HasColumnType("integer");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CachedAt")
                        .HasDatabaseName("idx_series_cachedat");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasDatabaseName("idx_series_tmdbid");

                    b.HasIndex("TmdbRating", "TmdbPopularity")
                        .HasDatabaseName("idx_series_rating_popularity");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("swipefilm.Models.SeriesSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TmdbSeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "SeasonNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_seriesseasons_seriesid_seasonnumber");

                    b.ToTable("SeriesSeasons");
                });

            modelBuilder.Entity("swipefilm.Models.SeriesWatchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstWatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastWatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeriesSeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("UserRating")
                        .HasColumnType("integer");

                    b.Property<int>("WatchedEpisodeCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeriesSeasonId");

                    b.HasIndex("ServerId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_seriesswatchhistory_userid");

                    b.HasIndex("UserId", "IsFavorite")
                        .HasDatabaseName("idx_serieswatchhistory_userid_isfavorite");

                    b.HasIndex("UserId", "SeriesSeasonId")
                        .IsUnique()
                        .HasDatabaseName("idx_serieswatchhistory_userid_seasonid");

                    b.HasIndex("UserId", "ServerId")
                        .HasDatabaseName("idx_serieswatchhistory_userid_serverid");

                    b.ToTable("SeriesWatchHistory");
                });

            modelBuilder.Entity("swipefilm.Models.ServerMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServerItemId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("ServerId", "MovieId")
                        .IsUnique()
                        .HasDatabaseName("idx_servermovie_server_movie");

                    b.ToTable("ServerMovie");
                });

            modelBuilder.Entity("swipefilm.Models.ServerSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServerItemId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("ServerId", "SeriesId")
                        .IsUnique()
                        .HasDatabaseName("idx_serverseries_serverid_seriesid");

                    b.ToTable("ServerSeries");
                });

            modelBuilder.Entity("swipefilm.Models.ServerSeriesSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeriesSeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeriesSeasonId");

                    b.HasIndex("ServerId", "SeriesSeasonId")
                        .IsUnique()
                        .HasDatabaseName("idx_serverseriesseasons_serverid_seasonid");

                    b.ToTable("ServerSeriesSeasons");
                });

            modelBuilder.Entity("swipefilm.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("swipefilm.Models.SessionMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionMatches");
                });

            modelBuilder.Entity("swipefilm.Models.SessionMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("SessionMembers");
                });

            modelBuilder.Entity("swipefilm.Models.Swipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContextMode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_swipes_userid");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("idx_swipes_userid_createdat");

                    b.HasIndex("UserId", "Direction")
                        .HasDatabaseName("idx_swipes_userid_direction");

                    b.ToTable("Swipes", t =>
                        {
                            t.HasCheckConstraint("ck_swipes_movie_xor_series", "(\"MovieId\" IS NOT NULL) <> (\"SeriesId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("swipefilm.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, int>>("ActorCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, float>>("ActorWeights")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<float>("AvgCompletionRate")
                        .HasColumnType("real");

                    b.Property<float>("AvgUserRating")
                        .HasColumnType("real");

                    b.Property<Dictionary<string, int>>("DirectorCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, float>>("DirectorWeights")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, int>>("GenreCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, float>>("GenreWeights")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<float>("IndieVsBlockbuster")
                        .HasColumnType("real");

                    b.Property<Dictionary<string, int>>("KeywordCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, float>>("KeywordWeights")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, int>>("LanguageCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, float>>("OriginalLanguageWeights")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, float>>("PreferredDecadeWeights")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<float>("PreferredMinYear")
                        .HasColumnType("real");

                    b.Property<float>("PreferredRuntimeMax")
                        .HasColumnType("real");

                    b.Property<float>("RepeatViewRate")
                        .HasColumnType("real");

                    b.Property<int>("TotalSignals")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_userprofiles_userid");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("swipefilm.Models.UserRadarr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultQualityProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultQualityProfileName")
                        .HasColumnType("text");

                    b.Property<string>("DefaultRootFolderPath")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UrlEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRadarr");
                });

            modelBuilder.Entity("swipefilm.Models.UserSeerr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UrlEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSeerr");
                });

            modelBuilder.Entity("swipefilm.Models.UserSeriesProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, int>>("ActorCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, float>>("ActorWeights")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<float>("AvgSeasonCompletionRate")
                        .HasColumnType("real");

                    b.Property<float>("AvgSeasonsWatchedRatio")
                        .HasColumnType("real");

                    b.Property<Dictionary<string, int>>("CreatorCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, float>>("CreatorWeights")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, int>>("GenreCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, float>>("GenreWeights")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, int>>("KeywordCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, float>>("KeywordWeights")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, int>>("LanguageCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, float>>("OriginalLanguageWeights")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, float>>("PreferredDecadeWeights")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TotalSeriesSignals")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_userseriesprofiles_userid");

                    b.ToTable("UserSeriesProfiles");
                });

            modelBuilder.Entity("swipefilm.Models.UserServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("TokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UrlEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("idx_userservers_userid_isactive");

                    b.ToTable("UserServers");
                });

            modelBuilder.Entity("swipefilm.Models.UserSonarr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultQualityProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultQualityProfileName")
                        .HasColumnType("text");

                    b.Property<string>("DefaultRootFolderPath")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UrlEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSonarr");
                });

            modelBuilder.Entity("swipefilm.Models.WatchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AbandonedAtSec")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstWatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastWatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("UserRating")
                        .HasColumnType("integer");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.Property<int>("WatchDurationSec")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("idx_watchhistory_movieid");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("idx_watchhistory_serverid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_watchhistory_userid");

                    b.HasIndex("UserId", "IsFavorite")
                        .HasDatabaseName("idx_watchhistory_userid_isfavorite");

                    b.HasIndex("UserId", "ServerId")
                        .HasDatabaseName("idx_watchhistory_userid_serverid");

                    b.ToTable("WatchHistory");
                });

            modelBuilder.Entity("swipefilm.Models.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RemindedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_watchlists_userid");

                    b.ToTable("Watchlists", t =>
                        {
                            t.HasCheckConstraint("ck_watchlists_movie_xor_series", "(\"MovieId\" IS NOT NULL) <> (\"SeriesId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("swipefilm.Models.MediaRequest", b =>
                {
                    b.HasOne("swipefilm.Models.Movie", "Movie")
                        .WithMany("Requests")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("User", "ProcessedBy")
                        .WithMany()
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("swipefilm.Models.Series", "Series")
                        .WithMany("Requests")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("ProcessedBy");

                    b.Navigation("Series");

                    b.Navigation("User");
                });

            modelBuilder.Entity("swipefilm.Models.MediaRequestSeason", b =>
                {
                    b.HasOne("swipefilm.Models.MediaRequest", "MediaRequest")
                        .WithMany("Seasons")
                        .HasForeignKey("MediaRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaRequest");
                });

            modelBuilder.Entity("swipefilm.Models.SeriesSeason", b =>
                {
                    b.HasOne("swipefilm.Models.Series", "Series")
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("swipefilm.Models.SeriesWatchHistory", b =>
                {
                    b.HasOne("swipefilm.Models.SeriesSeason", "SeriesSeason")
                        .WithMany()
                        .HasForeignKey("SeriesSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("swipefilm.Models.UserServer", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeriesSeason");

                    b.Navigation("Server");

                    b.Navigation("User");
                });

            modelBuilder.Entity("swipefilm.Models.ServerMovie", b =>
                {
                    b.HasOne("swipefilm.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("swipefilm.Models.UserServer", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("swipefilm.Models.ServerSeries", b =>
                {
                    b.HasOne("swipefilm.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("swipefilm.Models.UserServer", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("swipefilm.Models.ServerSeriesSeason", b =>
                {
                    b.HasOne("swipefilm.Models.SeriesSeason", "SeriesSeason")
                        .WithMany()
                        .HasForeignKey("SeriesSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("swipefilm.Models.UserServer", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeriesSeason");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("swipefilm.Models.Session", b =>
                {
                    b.HasOne("User", "CreatedBy")
                        .WithMany("CreatedSessions")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("swipefilm.Models.SessionMatch", b =>
                {
                    b.HasOne("swipefilm.Models.Movie", "Movie")
                        .WithMany("SessionMatches")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("swipefilm.Models.Session", "Session")
                        .WithMany("Matches")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("swipefilm.Models.SessionMember", b =>
                {
                    b.HasOne("swipefilm.Models.Session", "Session")
                        .WithMany("Members")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("SessionMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("swipefilm.Models.Swipe", b =>
                {
                    b.HasOne("swipefilm.Models.Movie", "Movie")
                        .WithMany("Swipes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("swipefilm.Models.Series", "Series")
                        .WithMany("Swipes")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("User", "User")
                        .WithMany("Swipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Series");

                    b.Navigation("User");
                });

            modelBuilder.Entity("swipefilm.Models.UserProfile", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("swipefilm.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("swipefilm.Models.UserRadarr", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("swipefilm.Models.UserSeerr", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("Seerr")
                        .HasForeignKey("swipefilm.Models.UserSeerr", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("swipefilm.Models.UserSeriesProfile", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("SeriesProfile")
                        .HasForeignKey("swipefilm.Models.UserSeriesProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("swipefilm.Models.UserServer", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Servers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("swipefilm.Models.UserSonarr", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("swipefilm.Models.WatchHistory", b =>
                {
                    b.HasOne("swipefilm.Models.Movie", "Movie")
                        .WithMany("WatchHistory")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("swipefilm.Models.UserServer", "Server")
                        .WithMany("WatchHistory")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("WatchHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Server");

                    b.Navigation("User");
                });

            modelBuilder.Entity("swipefilm.Models.Watchlist", b =>
                {
                    b.HasOne("swipefilm.Models.Movie", "Movie")
                        .WithMany("Watchlists")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("swipefilm.Models.Series", "Series")
                        .WithMany("Watchlists")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("User", "User")
                        .WithMany("Watchlist")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Series");

                    b.Navigation("User");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("CreatedSessions");

                    b.Navigation("Profile");

                    b.Navigation("Requests");

                    b.Navigation("Seerr");

                    b.Navigation("SeriesProfile");

                    b.Navigation("Servers");

                    b.Navigation("SessionMemberships");

                    b.Navigation("Swipes");

                    b.Navigation("WatchHistory");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("swipefilm.Models.MediaRequest", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("swipefilm.Models.Movie", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("SessionMatches");

                    b.Navigation("Swipes");

                    b.Navigation("WatchHistory");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("swipefilm.Models.Series", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("Seasons");

                    b.Navigation("Swipes");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("swipefilm.Models.Session", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("swipefilm.Models.UserServer", b =>
                {
                    b.Navigation("WatchHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
